workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: .
        script: ./gradlew tasks
      - name: Build Android APK
        working_directory: .
        script: ./gradlew build
    artifacts:
      - app/build/outputs/**/**/*.apk
